// AI / ML knowledge base — concept MCQs from fundamentals → advanced → latest,
// plus how AI/ML applies across disciplines (PM, Marketing, Sales, Design, Ops).
// disciplineId is "aiml" so /learn can surface it as its own knowledge base.
import type { MCQ } from "./quiz";

export const AIML_BANK: MCQ[] = [
  // ───────────────── FUNDAMENTALS ─────────────────
  { id: "ai-f-1", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "What is the core difference between supervised and unsupervised learning?",
    options: ["Supervised uses labeled data; unsupervised finds structure in unlabeled data", "Supervised is faster", "Unsupervised always uses neural nets", "There is no difference"], correctIndex: 0,
    explanation: "Supervised learning trains on input→label pairs; unsupervised learning finds patterns/clusters in data without labels.",
    source: "Andrew Ng — Machine Learning (Coursera); Hands-On ML (Géron)" },
  { id: "ai-f-2", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "Which best describes the relationship between AI, ML, and deep learning?",
    options: ["They're synonyms", "Deep learning ⊂ machine learning ⊂ AI", "AI ⊂ ML ⊂ deep learning", "They're unrelated fields"], correctIndex: 1,
    explanation: "Deep learning is a subset of ML, which is a subset of AI. DL uses multi-layer neural networks.",
    source: "Deep Learning (Goodfellow, Bengio, Courville)" },
  { id: "ai-f-3", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "What is 'reinforcement learning'?",
    options: ["Learning from labeled examples", "An agent learning via rewards/penalties from interacting with an environment", "Clustering similar data", "Compressing data"], correctIndex: 1,
    explanation: "RL trains an agent to maximize cumulative reward through trial-and-error interaction with an environment.",
    source: "Sutton & Barto — Reinforcement Learning: An Introduction" },

  // ───────────────── CORE ML CONCEPTS ─────────────────
  { id: "ai-ml-1", disciplineId: "aiml", topic: "ML Concepts",
    question: "Overfitting is when a model…",
    options: ["Is too simple to learn the pattern", "Memorizes training data and generalizes poorly to new data", "Trains too fast", "Has too little data"], correctIndex: 1,
    explanation: "Overfitting = low training error but high test error; the model captures noise. Fix with regularization, more data, simpler models.",
    source: "Hands-On ML (Géron); Andrew Ng" },
  { id: "ai-ml-2", disciplineId: "aiml", topic: "ML Concepts",
    question: "The bias-variance tradeoff says that as model complexity increases…",
    options: ["Both bias and variance rise", "Bias falls but variance rises", "Both fall forever", "Nothing changes"], correctIndex: 1,
    explanation: "More complex models reduce bias (underfitting) but increase variance (overfitting); the goal is the sweet spot.",
    source: "The Elements of Statistical Learning (Hastie, Tibshirani, Friedman)" },
  { id: "ai-ml-3", disciplineId: "aiml", topic: "ML Concepts",
    question: "Why do we hold out a separate test set?",
    options: ["To train faster", "To get an unbiased estimate of generalization to unseen data", "To increase accuracy", "It's optional"], correctIndex: 1,
    explanation: "Evaluating on data the model never trained on estimates real-world performance; tuning on test data leaks information.",
    source: "Hands-On ML (Géron)" },
  { id: "ai-ml-4", disciplineId: "aiml", topic: "ML Concepts",
    question: "For a highly imbalanced classification problem, which metric is most misleading?",
    options: ["Precision", "Recall", "Accuracy", "F1 score"], correctIndex: 2,
    explanation: "With 99% negatives, predicting 'all negative' gives 99% accuracy but is useless. Use precision/recall, F1, or PR-AUC.",
    source: "Designing Machine Learning Systems (Chip Huyen)" },
  { id: "ai-ml-5", disciplineId: "aiml", topic: "ML Concepts",
    question: "What does regularization (e.g. L1/L2) primarily do?",
    options: ["Speeds up training", "Penalizes model complexity to reduce overfitting", "Adds more features", "Increases learning rate"], correctIndex: 1,
    explanation: "Regularization adds a penalty on weight magnitude, discouraging overly complex models. L1 also drives sparsity.",
    source: "The Elements of Statistical Learning" },

  // ───────────────── DEEP LEARNING ─────────────────
  { id: "ai-dl-1", disciplineId: "aiml", topic: "Deep Learning",
    question: "What is backpropagation?",
    options: ["A data-loading technique", "The algorithm that computes gradients to update network weights via the chain rule", "A type of neural layer", "A loss function"], correctIndex: 1,
    explanation: "Backprop propagates the loss gradient backward through the network (chain rule) so gradient descent can update weights.",
    source: "Deep Learning (Goodfellow et al.)" },
  { id: "ai-dl-2", disciplineId: "aiml", topic: "Deep Learning",
    question: "A CNN (convolutional neural network) is especially suited for…",
    options: ["Tabular data", "Images / spatial data", "Time series only", "Text only"], correctIndex: 1,
    explanation: "CNNs use convolutional filters to capture local spatial patterns, making them strong for images and vision tasks.",
    source: "Deep Learning (Goodfellow et al.)" },
  { id: "ai-dl-3", disciplineId: "aiml", topic: "Deep Learning",
    question: "What problem does an activation function like ReLU solve?",
    options: ["It stores data", "It introduces non-linearity so networks can model complex functions", "It speeds up I/O", "It labels data"], correctIndex: 1,
    explanation: "Without non-linear activations, stacked layers collapse to a linear model. ReLU adds non-linearity and avoids vanishing gradients better than sigmoid.",
    source: "Deep Learning (Goodfellow et al.)" },

  // ───────────────── LLMs & GENERATIVE AI (latest) ─────────────────
  { id: "ai-llm-1", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "The Transformer architecture's key innovation is…",
    options: ["Convolutions", "The self-attention mechanism", "Recurrence", "Decision trees"], correctIndex: 1,
    explanation: "'Attention Is All You Need' replaced recurrence with self-attention, enabling parallel training and long-range context.",
    source: "Vaswani et al. 2017 — Attention Is All You Need (https://arxiv.org/abs/1706.03762)" },
  { id: "ai-llm-2", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is a 'token' in the context of an LLM?",
    options: ["A password", "A chunk of text (word/subword) the model processes", "A neuron", "A GPU", ], correctIndex: 1,
    explanation: "LLMs operate on tokens — subword units. Context windows, pricing, and limits are measured in tokens.",
    source: "OpenAI / Anthropic developer docs" },
  { id: "ai-llm-3", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is the difference between pre-training and fine-tuning?",
    options: ["They're the same", "Pre-training learns general language from massive data; fine-tuning adapts the model to a specific task/domain", "Fine-tuning happens first", "Pre-training uses labels only"], correctIndex: 1,
    explanation: "Pre-training builds broad capability on large corpora; fine-tuning (or instruction-tuning/RLHF) specializes or aligns the model.",
    source: "Deep Learning literature; OpenAI/Anthropic model docs" },
  { id: "ai-llm-4", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "An LLM 'hallucination' is…",
    options: ["A hardware fault", "Confidently producing false or fabricated information", "Slow output", "A type of prompt"], correctIndex: 1,
    explanation: "Hallucination = plausible-sounding but incorrect/fabricated output. Mitigate with grounding (RAG), citations, and verification.",
    source: "Industry consensus; Anthropic/OpenAI safety docs" },
  { id: "ai-llm-5", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is RLHF?",
    options: ["A database", "Reinforcement Learning from Human Feedback — aligning model outputs to human preferences", "A GPU type", "A prompt format"], correctIndex: 1,
    explanation: "RLHF trains a reward model from human preference data, then optimizes the LLM against it — key to making models helpful and aligned.",
    source: "Christiano et al.; Ouyang et al. 2022 (InstructGPT)" },
  { id: "ai-llm-6", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "'Temperature' in LLM sampling controls…",
    options: ["Model size", "Randomness/creativity of outputs (higher = more varied)", "Token limit", "Training speed"], correctIndex: 1,
    explanation: "Lower temperature → more deterministic/focused; higher → more diverse/creative. (Note: some newer models remove sampling params.)",
    source: "LLM API documentation (OpenAI/Anthropic)" },

  // ───────────────── RAG & AGENTS (latest) ─────────────────
  { id: "ai-rag-1", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What problem does Retrieval-Augmented Generation (RAG) primarily address?",
    options: ["Slow GPUs", "Grounding LLM answers in external/up-to-date knowledge to reduce hallucination", "Tokenization", "Model training cost"], correctIndex: 1,
    explanation: "RAG retrieves relevant documents (often via a vector DB) and feeds them as context, grounding answers in real, current data.",
    source: "Lewis et al. 2020 — Retrieval-Augmented Generation (https://arxiv.org/abs/2005.11401)" },
  { id: "ai-rag-2", disciplineId: "aiml", topic: "RAG & Agents",
    question: "In a RAG pipeline, a vector database is used to…",
    options: ["Store model weights", "Find semantically similar text via embedding similarity search", "Train the model", "Render the UI"], correctIndex: 1,
    explanation: "Text is embedded into vectors; the vector DB does nearest-neighbor search to retrieve semantically relevant chunks.",
    source: "Industry practice (Pinecone/Weaviate/pgvector docs)" },
  { id: "ai-rag-3", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What characterizes an LLM 'agent' versus a single prompt?",
    options: ["It's larger", "It plans and takes multi-step actions using tools, observing results in a loop", "It runs offline", "It has no memory"], correctIndex: 1,
    explanation: "Agents use the LLM to reason, call tools, observe outputs, and iterate toward a goal — beyond a one-shot response.",
    source: "Anthropic 'Building effective agents'; ReAct (Yao et al. 2022)" },
  { id: "ai-rag-4", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What is 'prompt engineering'?",
    options: ["Building GPUs", "Designing inputs/instructions to elicit better LLM outputs", "Training from scratch", "Database indexing"], correctIndex: 1,
    explanation: "Crafting clear instructions, examples (few-shot), and structure to steer model behavior — often cheaper than fine-tuning.",
    source: "Anthropic/OpenAI prompting guides" },
  { id: "ai-rag-5", disciplineId: "aiml", topic: "RAG & Agents",
    question: "'Chain-of-thought' prompting improves reasoning by…",
    options: ["Making outputs shorter", "Asking the model to show step-by-step reasoning before the answer", "Lowering temperature", "Adding more GPUs"], correctIndex: 1,
    explanation: "Encouraging intermediate reasoning steps improves accuracy on multi-step problems (Wei et al. 2022).",
    source: "Wei et al. 2022 — Chain-of-Thought Prompting (https://arxiv.org/abs/2201.11903)" },

  // ───────────────── MLOps & PRODUCTION ─────────────────
  { id: "ai-ops-1", disciplineId: "aiml", topic: "MLOps & Production",
    question: "'Model drift' (data drift) in production means…",
    options: ["The model file moved", "Real-world data distribution shifts away from training data, degrading performance", "GPU overheating", "A slow API"], correctIndex: 1,
    explanation: "When live data diverges from training data, accuracy degrades. Detect with monitoring; fix with retraining.",
    source: "Designing Machine Learning Systems (Chip Huyen)" },
  { id: "ai-ops-2", disciplineId: "aiml", topic: "MLOps & Production",
    question: "Why are 'evals' critical when shipping LLM features?",
    options: ["They train the model", "They systematically measure output quality so you can compare prompts/models and catch regressions", "They reduce token cost", "They're not needed"], correctIndex: 1,
    explanation: "Without evaluation datasets and metrics (incl. LLM-as-judge), you can't tell if a change helps or quietly regresses quality.",
    source: "Industry practice; Anthropic/OpenAI eval guidance" },

  // ───────────────── ETHICS & SAFETY ─────────────────
  { id: "ai-eth-1", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "A common source of bias in ML models is…",
    options: ["Too many GPUs", "Biased or unrepresentative training data", "Low temperature", "Small token limits"], correctIndex: 1,
    explanation: "Models learn the biases present in their training data; representative data, audits, and fairness metrics help mitigate it.",
    source: "Fairness & ML literature; NIST AI RMF" },
  { id: "ai-eth-2", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "In AI safety, 'alignment' refers to…",
    options: ["GPU placement", "Making AI systems pursue intended human goals/values", "Aligning text on screen", "Data formatting"], correctIndex: 1,
    explanation: "Alignment is ensuring a model's objectives and behavior match human intent — the goal behind RLHF, Constitutional AI, etc.",
    source: "Anthropic — Constitutional AI; AI alignment research" },

  // ───────────────── AI ACROSS DISCIPLINES ─────────────────
  { id: "ai-pm-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "For an AI PM, a key difference in building AI products vs traditional products is…",
    options: ["No need for metrics", "Probabilistic outputs require designing for uncertainty, evals, and graceful failure", "They never need data", "Users don't matter"], correctIndex: 1,
    explanation: "AI features are non-deterministic; AI PMs must design for confidence/uncertainty, set up evals, handle errors, and manage data/feedback loops.",
    source: "Reforge / Lenny's Newsletter — AI PM practices" },
  { id: "ai-mkt-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "A responsible use of generative AI in marketing is…",
    options: ["Auto-publishing unreviewed claims", "Drafting/personalizing content with human review and brand/factual checks", "Replacing all strategy", "Ignoring disclosure rules"], correctIndex: 1,
    explanation: "GenAI accelerates content/personalization, but human review for accuracy, brand voice, and disclosure remains essential.",
    source: "Industry practice; FTC guidance on AI claims" },
  { id: "ai-sales-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "How is AI most commonly applied in modern sales workflows?",
    options: ["Replacing all reps", "Lead scoring, call summarization, and next-best-action recommendations", "Only for invoicing", "It isn't used"], correctIndex: 1,
    explanation: "AI augments reps: prioritizing leads, transcribing/summarizing calls, drafting follow-ups, and surfacing recommended actions.",
    source: "Industry practice (Gong, Salesforce Einstein)" },
  { id: "ai-design-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "A key UX challenge unique to designing AI features is…",
    options: ["Choosing fonts", "Communicating uncertainty and setting the right user expectations for imperfect output", "Picking colors", "Reducing whitespace"], correctIndex: 1,
    explanation: "AI UX must convey confidence, allow correction/feedback, and design for failure — users shouldn't over-trust probabilistic output.",
    source: "Google PAIR — People + AI Guidebook" },
  { id: "ai-data-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "When evaluating an LLM feature, 'LLM-as-a-judge' means…",
    options: ["The model decides pricing", "Using a strong LLM to score outputs against a rubric at scale", "A courtroom AI", "Auto-deleting bad data"], correctIndex: 1,
    explanation: "An LLM grades generated outputs against criteria — scalable for evals, though it needs calibration against human judgment.",
    source: "Industry eval practice; Zheng et al. 2023 (MT-Bench/LLM-as-judge)" },
];

export function aimlTopics(): string[] {
  return Array.from(new Set(AIML_BANK.map((m) => m.topic)));
}
