// AI / ML knowledge base — concept MCQs from fundamentals → advanced → latest,
// plus how AI/ML applies across disciplines (PM, Marketing, Sales, Design, Ops).
// disciplineId is "aiml" so /learn can surface it as its own knowledge base.
import type { MCQ } from "./quiz";

export const AIML_BANK: MCQ[] = [
  // ───────────────── FUNDAMENTALS ─────────────────
  { id: "ai-f-1", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "What is the core difference between supervised and unsupervised learning?",
    options: ["Supervised uses labeled data; unsupervised finds structure in unlabeled data", "Supervised is faster", "Unsupervised always uses neural nets", "There is no difference"], correctIndex: 0,
    explanation: "Supervised learning trains on input→label pairs; unsupervised learning finds patterns/clusters in data without labels.",
    source: "Andrew Ng — Machine Learning (Coursera); Hands-On ML (Géron)" },
  { id: "ai-f-2", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "Which best describes the relationship between AI, ML, and deep learning?",
    options: ["They're synonyms", "Deep learning ⊂ machine learning ⊂ AI", "AI ⊂ ML ⊂ deep learning", "They're unrelated fields"], correctIndex: 1,
    explanation: "Deep learning is a subset of ML, which is a subset of AI. DL uses multi-layer neural networks.",
    source: "Deep Learning (Goodfellow, Bengio, Courville)" },
  { id: "ai-f-3", disciplineId: "aiml", topic: "AI Fundamentals",
    question: "What is 'reinforcement learning'?",
    options: ["Learning from labeled examples", "An agent learning via rewards/penalties from interacting with an environment", "Clustering similar data", "Compressing data"], correctIndex: 1,
    explanation: "RL trains an agent to maximize cumulative reward through trial-and-error interaction with an environment.",
    source: "Sutton & Barto — Reinforcement Learning: An Introduction" },

  // ───────────────── CORE ML CONCEPTS ─────────────────
  { id: "ai-ml-1", disciplineId: "aiml", topic: "ML Concepts",
    question: "Overfitting is when a model…",
    options: ["Is too simple to learn the pattern", "Memorizes training data and generalizes poorly to new data", "Trains too fast", "Has too little data"], correctIndex: 1,
    explanation: "Overfitting = low training error but high test error; the model captures noise. Fix with regularization, more data, simpler models.",
    source: "Hands-On ML (Géron); Andrew Ng" },
  { id: "ai-ml-2", disciplineId: "aiml", topic: "ML Concepts",
    question: "The bias-variance tradeoff says that as model complexity increases…",
    options: ["Both bias and variance rise", "Bias falls but variance rises", "Both fall forever", "Nothing changes"], correctIndex: 1,
    explanation: "More complex models reduce bias (underfitting) but increase variance (overfitting); the goal is the sweet spot.",
    source: "The Elements of Statistical Learning (Hastie, Tibshirani, Friedman)" },
  { id: "ai-ml-3", disciplineId: "aiml", topic: "ML Concepts",
    question: "Why do we hold out a separate test set?",
    options: ["To train faster", "To get an unbiased estimate of generalization to unseen data", "To increase accuracy", "It's optional"], correctIndex: 1,
    explanation: "Evaluating on data the model never trained on estimates real-world performance; tuning on test data leaks information.",
    source: "Hands-On ML (Géron)" },
  { id: "ai-ml-4", disciplineId: "aiml", topic: "ML Concepts",
    question: "For a highly imbalanced classification problem, which metric is most misleading?",
    options: ["Precision", "Recall", "Accuracy", "F1 score"], correctIndex: 2,
    explanation: "With 99% negatives, predicting 'all negative' gives 99% accuracy but is useless. Use precision/recall, F1, or PR-AUC.",
    source: "Designing Machine Learning Systems (Chip Huyen)" },
  { id: "ai-ml-5", disciplineId: "aiml", topic: "ML Concepts",
    question: "What does regularization (e.g. L1/L2) primarily do?",
    options: ["Speeds up training", "Penalizes model complexity to reduce overfitting", "Adds more features", "Increases learning rate"], correctIndex: 1,
    explanation: "Regularization adds a penalty on weight magnitude, discouraging overly complex models. L1 also drives sparsity.",
    source: "The Elements of Statistical Learning" },

  // ───────────────── DEEP LEARNING ─────────────────
  { id: "ai-dl-1", disciplineId: "aiml", topic: "Deep Learning",
    question: "What is backpropagation?",
    options: ["A data-loading technique", "The algorithm that computes gradients to update network weights via the chain rule", "A type of neural layer", "A loss function"], correctIndex: 1,
    explanation: "Backprop propagates the loss gradient backward through the network (chain rule) so gradient descent can update weights.",
    source: "Deep Learning (Goodfellow et al.)" },
  { id: "ai-dl-2", disciplineId: "aiml", topic: "Deep Learning",
    question: "A CNN (convolutional neural network) is especially suited for…",
    options: ["Tabular data", "Images / spatial data", "Time series only", "Text only"], correctIndex: 1,
    explanation: "CNNs use convolutional filters to capture local spatial patterns, making them strong for images and vision tasks.",
    source: "Deep Learning (Goodfellow et al.)" },
  { id: "ai-dl-3", disciplineId: "aiml", topic: "Deep Learning",
    question: "What problem does an activation function like ReLU solve?",
    options: ["It stores data", "It introduces non-linearity so networks can model complex functions", "It speeds up I/O", "It labels data"], correctIndex: 1,
    explanation: "Without non-linear activations, stacked layers collapse to a linear model. ReLU adds non-linearity and avoids vanishing gradients better than sigmoid.",
    source: "Deep Learning (Goodfellow et al.)" },

  // ───────────────── LLMs & GENERATIVE AI (latest) ─────────────────
  { id: "ai-llm-1", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "The Transformer architecture's key innovation is…",
    options: ["Convolutions", "The self-attention mechanism", "Recurrence", "Decision trees"], correctIndex: 1,
    explanation: "'Attention Is All You Need' replaced recurrence with self-attention, enabling parallel training and long-range context.",
    source: "Vaswani et al. 2017 — Attention Is All You Need (https://arxiv.org/abs/1706.03762)" },
  { id: "ai-llm-2", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is a 'token' in the context of an LLM?",
    options: ["A password", "A chunk of text (word/subword) the model processes", "A neuron", "A GPU", ], correctIndex: 1,
    explanation: "LLMs operate on tokens — subword units. Context windows, pricing, and limits are measured in tokens.",
    source: "OpenAI / Anthropic developer docs" },
  { id: "ai-llm-3", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is the difference between pre-training and fine-tuning?",
    options: ["They're the same", "Pre-training learns general language from massive data; fine-tuning adapts the model to a specific task/domain", "Fine-tuning happens first", "Pre-training uses labels only"], correctIndex: 1,
    explanation: "Pre-training builds broad capability on large corpora; fine-tuning (or instruction-tuning/RLHF) specializes or aligns the model.",
    source: "Deep Learning literature; OpenAI/Anthropic model docs" },
  { id: "ai-llm-4", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "An LLM 'hallucination' is…",
    options: ["A hardware fault", "Confidently producing false or fabricated information", "Slow output", "A type of prompt"], correctIndex: 1,
    explanation: "Hallucination = plausible-sounding but incorrect/fabricated output. Mitigate with grounding (RAG), citations, and verification.",
    source: "Industry consensus; Anthropic/OpenAI safety docs" },
  { id: "ai-llm-5", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "What is RLHF?",
    options: ["A database", "Reinforcement Learning from Human Feedback — aligning model outputs to human preferences", "A GPU type", "A prompt format"], correctIndex: 1,
    explanation: "RLHF trains a reward model from human preference data, then optimizes the LLM against it — key to making models helpful and aligned.",
    source: "Christiano et al.; Ouyang et al. 2022 (InstructGPT)" },
  { id: "ai-llm-6", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "'Temperature' in LLM sampling controls…",
    options: ["Model size", "Randomness/creativity of outputs (higher = more varied)", "Token limit", "Training speed"], correctIndex: 1,
    explanation: "Lower temperature → more deterministic/focused; higher → more diverse/creative. (Note: some newer models remove sampling params.)",
    source: "LLM API documentation (OpenAI/Anthropic)" },

  // ───────────────── RAG & AGENTS (latest) ─────────────────
  { id: "ai-rag-1", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What problem does Retrieval-Augmented Generation (RAG) primarily address?",
    options: ["Slow GPUs", "Grounding LLM answers in external/up-to-date knowledge to reduce hallucination", "Tokenization", "Model training cost"], correctIndex: 1,
    explanation: "RAG retrieves relevant documents (often via a vector DB) and feeds them as context, grounding answers in real, current data.",
    source: "Lewis et al. 2020 — Retrieval-Augmented Generation (https://arxiv.org/abs/2005.11401)" },
  { id: "ai-rag-2", disciplineId: "aiml", topic: "RAG & Agents",
    question: "In a RAG pipeline, a vector database is used to…",
    options: ["Store model weights", "Find semantically similar text via embedding similarity search", "Train the model", "Render the UI"], correctIndex: 1,
    explanation: "Text is embedded into vectors; the vector DB does nearest-neighbor search to retrieve semantically relevant chunks.",
    source: "Industry practice (Pinecone/Weaviate/pgvector docs)" },
  { id: "ai-rag-3", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What characterizes an LLM 'agent' versus a single prompt?",
    options: ["It's larger", "It plans and takes multi-step actions using tools, observing results in a loop", "It runs offline", "It has no memory"], correctIndex: 1,
    explanation: "Agents use the LLM to reason, call tools, observe outputs, and iterate toward a goal — beyond a one-shot response.",
    source: "Anthropic 'Building effective agents'; ReAct (Yao et al. 2022)" },
  { id: "ai-rag-4", disciplineId: "aiml", topic: "RAG & Agents",
    question: "What is 'prompt engineering'?",
    options: ["Building GPUs", "Designing inputs/instructions to elicit better LLM outputs", "Training from scratch", "Database indexing"], correctIndex: 1,
    explanation: "Crafting clear instructions, examples (few-shot), and structure to steer model behavior — often cheaper than fine-tuning.",
    source: "Anthropic/OpenAI prompting guides" },
  { id: "ai-rag-5", disciplineId: "aiml", topic: "RAG & Agents",
    question: "'Chain-of-thought' prompting improves reasoning by…",
    options: ["Making outputs shorter", "Asking the model to show step-by-step reasoning before the answer", "Lowering temperature", "Adding more GPUs"], correctIndex: 1,
    explanation: "Encouraging intermediate reasoning steps improves accuracy on multi-step problems (Wei et al. 2022).",
    source: "Wei et al. 2022 — Chain-of-Thought Prompting (https://arxiv.org/abs/2201.11903)" },

  // ───────────────── MLOps & PRODUCTION ─────────────────
  { id: "ai-ops-1", disciplineId: "aiml", topic: "MLOps & Production",
    question: "'Model drift' (data drift) in production means…",
    options: ["The model file moved", "Real-world data distribution shifts away from training data, degrading performance", "GPU overheating", "A slow API"], correctIndex: 1,
    explanation: "When live data diverges from training data, accuracy degrades. Detect with monitoring; fix with retraining.",
    source: "Designing Machine Learning Systems (Chip Huyen)" },
  { id: "ai-ops-2", disciplineId: "aiml", topic: "MLOps & Production",
    question: "Why are 'evals' critical when shipping LLM features?",
    options: ["They train the model", "They systematically measure output quality so you can compare prompts/models and catch regressions", "They reduce token cost", "They're not needed"], correctIndex: 1,
    explanation: "Without evaluation datasets and metrics (incl. LLM-as-judge), you can't tell if a change helps or quietly regresses quality.",
    source: "Industry practice; Anthropic/OpenAI eval guidance" },

  // ───────────────── ETHICS & SAFETY ─────────────────
  { id: "ai-eth-1", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "A common source of bias in ML models is…",
    options: ["Too many GPUs", "Biased or unrepresentative training data", "Low temperature", "Small token limits"], correctIndex: 1,
    explanation: "Models learn the biases present in their training data; representative data, audits, and fairness metrics help mitigate it.",
    source: "Fairness & ML literature; NIST AI RMF" },
  { id: "ai-eth-2", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "In AI safety, 'alignment' refers to…",
    options: ["GPU placement", "Making AI systems pursue intended human goals/values", "Aligning text on screen", "Data formatting"], correctIndex: 1,
    explanation: "Alignment is ensuring a model's objectives and behavior match human intent — the goal behind RLHF, Constitutional AI, etc.",
    source: "Anthropic — Constitutional AI; AI alignment research" },

  // ───────────────── AI ACROSS DISCIPLINES ─────────────────
  { id: "ai-pm-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "For an AI PM, a key difference in building AI products vs traditional products is…",
    options: ["No need for metrics", "Probabilistic outputs require designing for uncertainty, evals, and graceful failure", "They never need data", "Users don't matter"], correctIndex: 1,
    explanation: "AI features are non-deterministic; AI PMs must design for confidence/uncertainty, set up evals, handle errors, and manage data/feedback loops.",
    source: "Reforge / Lenny's Newsletter — AI PM practices" },
  { id: "ai-mkt-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "A responsible use of generative AI in marketing is…",
    options: ["Auto-publishing unreviewed claims", "Drafting/personalizing content with human review and brand/factual checks", "Replacing all strategy", "Ignoring disclosure rules"], correctIndex: 1,
    explanation: "GenAI accelerates content/personalization, but human review for accuracy, brand voice, and disclosure remains essential.",
    source: "Industry practice; FTC guidance on AI claims" },
  { id: "ai-sales-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "How is AI most commonly applied in modern sales workflows?",
    options: ["Replacing all reps", "Lead scoring, call summarization, and next-best-action recommendations", "Only for invoicing", "It isn't used"], correctIndex: 1,
    explanation: "AI augments reps: prioritizing leads, transcribing/summarizing calls, drafting follow-ups, and surfacing recommended actions.",
    source: "Industry practice (Gong, Salesforce Einstein)" },
  { id: "ai-design-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "A key UX challenge unique to designing AI features is…",
    options: ["Choosing fonts", "Communicating uncertainty and setting the right user expectations for imperfect output", "Picking colors", "Reducing whitespace"], correctIndex: 1,
    explanation: "AI UX must convey confidence, allow correction/feedback, and design for failure — users shouldn't over-trust probabilistic output.",
    source: "Google PAIR — People + AI Guidebook" },
  { id: "ai-data-1", disciplineId: "aiml", topic: "AI across disciplines",
    question: "When evaluating an LLM feature, 'LLM-as-a-judge' means…",
    options: ["The model decides pricing", "Using a strong LLM to score outputs against a rubric at scale", "A courtroom AI", "Auto-deleting bad data"], correctIndex: 1,
    explanation: "An LLM grades generated outputs against criteria — scalable for evals, though it needs calibration against human judgment.",
    source: "Industry eval practice; Zheng et al. 2023 (MT-Bench/LLM-as-judge)" },

  // ───────────────── 2026 AI / GENAI EXPANSION ─────────────────
  { id: "ai-x-llm-1", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "Why does a larger context window not automatically solve hallucinations?",
    options: ["The model ignores all context", "Retrieved context can be irrelevant, stale, conflicting, or misused during generation", "Long context is always free", "Hallucinations only happen in small models"], correctIndex: 1,
    explanation: "Long context helps only when the right evidence is included and the model uses it faithfully; evals must still measure grounding.",
    source: "Anthropic/OpenAI prompting docs; enterprise RAG practice" },
  { id: "ai-x-llm-2", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "The most product-relevant tradeoff when choosing a model is usually…",
    options: ["Name recognition only", "Quality, latency, cost, safety, and deployment constraints", "Number of vowels in the model name", "Whether it can write poems"], correctIndex: 1,
    explanation: "Production model choice is a product and systems tradeoff, not a leaderboard-only decision.",
    source: "KORE1 AI PM Interview Questions 2026; Cubitrek AI Engineer Questions 2026" },
  { id: "ai-x-llm-3", disciplineId: "aiml", topic: "LLMs & GenAI",
    question: "Prompt engineering is usually preferred over fine-tuning when…",
    options: ["You need to change model weights", "The task can be improved with instructions, examples, or context without new training data", "You need lower latency at any cost", "You want to delete evals"], correctIndex: 1,
    explanation: "Prompting is cheaper and faster for many behavior changes; fine-tuning is better for durable style/format/task adaptation with data.",
    source: "OpenAI/Anthropic prompting guides; ZeroPitch AI PM Guide 2026" },
  { id: "ai-x-rag-1", disciplineId: "aiml", topic: "RAG & Agents",
    question: "A strong RAG evaluation separates retrieval quality from…",
    options: ["File size", "Generation quality", "CSS quality", "GPU brand"], correctIndex: 1,
    explanation: "Retrieval can fail even if the model writes well, and generation can fail even if retrieval found the right evidence.",
    source: "KORE1 AI PM Interview Questions 2026; RAGAS evaluation practice" },
  { id: "ai-x-rag-2", disciplineId: "aiml", topic: "RAG & Agents",
    question: "Which metric best checks whether the right document appears near the top of retrieved results?",
    options: ["Temperature", "Recall@k / MRR", "DAU", "Training loss only"], correctIndex: 1,
    explanation: "Recall@k checks whether relevant evidence is retrieved; MRR rewards relevant evidence appearing earlier in the ranked list.",
    source: "Information retrieval metrics; enterprise RAG eval practice" },
  { id: "ai-x-rag-3", disciplineId: "aiml", topic: "RAG & Agents",
    question: "Hybrid search in RAG usually combines…",
    options: ["SQL and CSS", "Keyword search such as BM25 with dense vector similarity", "Two random LLMs", "Training and deployment"], correctIndex: 1,
    explanation: "Hybrid retrieval catches both exact terms/entities and semantic matches, often improving enterprise RAG recall.",
    source: "Cubitrek AI Engineer Questions 2026; vector database documentation" },
  { id: "ai-x-rag-4", disciplineId: "aiml", topic: "RAG & Agents",
    question: "A reranker in a RAG pipeline is used to…",
    options: ["Train embeddings from scratch", "Reorder candidate documents by relevance before generation", "Lower the model temperature", "Delete citations"], correctIndex: 1,
    explanation: "Retrievers often fetch a broad candidate set; rerankers improve the final context order and precision.",
    source: "Enterprise RAG practice; Cubitrek AI Engineer Questions 2026" },
  { id: "ai-x-agent-1", disciplineId: "aiml", topic: "RAG & Agents",
    question: "A deterministic workflow differs from an autonomous agent because a workflow…",
    options: ["Uses no software", "Follows predefined steps, while an agent chooses actions based on observations", "Is always worse", "Cannot call APIs"], correctIndex: 1,
    explanation: "Workflows are often more reliable when the path is known; agents are useful when the path must be discovered dynamically.",
    source: "Anthropic — Building Effective Agents" },
  { id: "ai-x-agent-2", disciplineId: "aiml", topic: "RAG & Agents",
    question: "Which is a practical guardrail for an LLM agent with tool access?",
    options: ["Unlimited tool permissions", "Least-privilege tool scopes and confirmation for high-impact actions", "No logging", "Hidden system prompts only"], correctIndex: 1,
    explanation: "Agents should have bounded tools, action confirmations, audit logs, and risk-based permissions.",
    source: "OWASP Top 10 for LLM Apps; Anthropic agent guidance" },
  { id: "ai-x-eval-1", disciplineId: "aiml", topic: "AI Evaluation",
    question: "A golden dataset for LLM evals is…",
    options: ["A production database password", "A curated set of representative inputs with expected outputs or rubrics", "A UI theme", "A model checkpoint"], correctIndex: 1,
    explanation: "Golden datasets let teams compare prompts/models and catch regressions against known cases.",
    source: "OpenAI/Anthropic eval guidance; Cubitrek AI Engineer Questions 2026" },
  { id: "ai-x-eval-2", disciplineId: "aiml", topic: "AI Evaluation",
    question: "Why calibrate LLM-as-a-judge against human labels?",
    options: ["To make it slower", "To detect judge bias and verify it matches human quality judgments", "To avoid rubrics", "To increase token limits"], correctIndex: 1,
    explanation: "LLM judges can prefer verbosity or exhibit bias; calibration checks whether automated scores are trustworthy enough.",
    source: "Zheng et al. 2023 MT-Bench; LLM eval practice" },
  { id: "ai-x-eval-3", disciplineId: "aiml", topic: "AI Evaluation",
    question: "A regression eval in CI/CD helps ensure that…",
    options: ["Every response is identical forever", "Prompt/model changes do not silently degrade important cases", "Users cannot give feedback", "All tests are manual"], correctIndex: 1,
    explanation: "AI changes can improve averages while breaking critical edge cases; regression evals catch those failures before deploy.",
    source: "Cubitrek AI Engineer Questions 2026; LLMOps practice" },
  { id: "ai-x-safety-1", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "Prompt injection is dangerous mainly because it can…",
    options: ["Change the website font", "Cause the model to ignore trusted instructions or misuse connected tools/data", "Only increase latency", "Disable GPUs"], correctIndex: 1,
    explanation: "Prompt injection treats untrusted content as instructions, which is especially risky for RAG and tool-using agents.",
    source: "OWASP Top 10 for LLM Applications" },
  { id: "ai-x-safety-2", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "The NIST AI RMF frames trustworthy AI using concepts such as…",
    options: ["Map, Measure, Manage, Govern", "Build, Ship, Forget, Repeat", "Prompt, Pray, Publish, Profit", "Click, Cache, Close, Commit"], correctIndex: 0,
    explanation: "NIST AI RMF emphasizes governing AI risks through mapping context, measuring risks, managing them, and governance.",
    source: "NIST AI Risk Management Framework" },
  { id: "ai-x-safety-3", disciplineId: "aiml", topic: "AI Ethics & Safety",
    question: "For high-risk AI actions, a good product pattern is…",
    options: ["Silent execution", "Human confirmation, audit logs, and rollback or escalation paths", "No user controls", "Hiding uncertainty"], correctIndex: 1,
    explanation: "Risky AI actions need user agency, traceability, and recovery paths, not just model confidence.",
    source: "Google PAIR; NIST AI RMF; Anthropic agent guidance" },
  { id: "ai-x-ops-1", disciplineId: "aiml", topic: "MLOps & Production",
    question: "Which metric is most directly tied to LLM serving cost?",
    options: ["Token volume", "Button color", "CSS bundle size", "NPS alone"], correctIndex: 0,
    explanation: "Input/output tokens drive most API-model costs; routing, compression, and caching reduce token spend.",
    source: "OpenAI/Anthropic API docs; AI production practice" },
  { id: "ai-x-ops-2", disciplineId: "aiml", topic: "MLOps & Production",
    question: "Model routing means…",
    options: ["Sending every request to the largest model", "Choosing models dynamically by task, cost, latency, risk, or quality needs", "Turning off evals", "Only changing UI routes"], correctIndex: 1,
    explanation: "Routing lets teams use cheap/fast models for easy tasks and stronger models for high-risk or hard cases.",
    source: "AI production architecture practice; Cubitrek AI Engineer Questions 2026" },
  { id: "ai-x-ops-3", disciplineId: "aiml", topic: "MLOps & Production",
    question: "A fallback in an AI product is…",
    options: ["A planned safe behavior when the model/system cannot confidently complete the task", "A design color", "A way to skip monitoring", "Always a second random answer"], correctIndex: 0,
    explanation: "Fallbacks can include asking clarifying questions, escalating to a human, using deterministic search, or refusing unsafe tasks.",
    source: "KORE1 AI PM Interview Questions 2026; production AI practice" },
  { id: "ai-x-data-1", disciplineId: "aiml", topic: "Data & Labeling",
    question: "Why version prompts, eval datasets, and model choices together?",
    options: ["To increase bureaucracy", "To make quality changes reproducible and debuggable", "To hide failures", "To avoid testing"], correctIndex: 1,
    explanation: "LLM behavior depends on prompt, model, data, and retrieval; versioning lets teams attribute regressions correctly.",
    source: "LLMOps practice; OpenAI/Anthropic eval guidance" },
  { id: "ai-x-data-2", disciplineId: "aiml", topic: "Data & Labeling",
    question: "Human feedback loops can go wrong when feedback is…",
    options: ["Biased, sparse, gamed, or unrepresentative", "Reviewed by experts", "Versioned", "Used with privacy controls"], correctIndex: 0,
    explanation: "Feedback is valuable but can reinforce biased samples or optimize for noisy user signals unless governed carefully.",
    source: "Google PAIR; human-in-the-loop ML practice" },
  { id: "ai-x-multi-1", disciplineId: "aiml", topic: "Multimodal AI",
    question: "A multimodal model can process…",
    options: ["Only SQL", "More than one modality such as text, images, audio, or video", "Only numbers", "Only labels"], correctIndex: 1,
    explanation: "Multimodal systems combine modalities, enabling tasks like image question answering or audio-to-text reasoning.",
    source: "Multimodal AI documentation; Google/Meta/OpenAI model docs" },
  { id: "ai-x-strat-1", disciplineId: "aiml", topic: "AI Strategy",
    question: "If foundation models are widely available, a product's AI moat is more likely to come from…",
    options: ["Using the word AI in marketing", "Proprietary data, workflow integration, feedback loops, trust, and distribution", "A hidden prompt only", "Ignoring UX"], correctIndex: 1,
    explanation: "Durable advantage often comes from data, workflows, customer trust, eval infrastructure, and distribution rather than model access alone.",
    source: "KORE1 AI PM Interview Questions 2026; AI product strategy practice" },
  { id: "ai-x-strat-2", disciplineId: "aiml", topic: "AI Strategy",
    question: "AI-washing means…",
    options: ["Using AI where it creates real user value", "Adding AI branding or an LLM where it does not solve the real problem", "Measuring model quality", "Designing safety reviews"], correctIndex: 1,
    explanation: "Good AI PMs know when not to use AI; AI-washing adds complexity without improving the user workflow.",
    source: "KORE1 PM Interview Questions 2026; ZeroPitch AI PM Guide 2026" },
];

export function aimlTopics(): string[] {
  return Array.from(new Set(AIML_BANK.map((m) => m.topic)));
}
